import type { Metadata } from "next";
import { ReactNode } from "react";
import { PostHogProviderWrapper } from "./client/PostHogProviderWrapper";
import { geistMono, geistSans } from "./fonts";
import "./globals.css";
import { getServerFeatureFlags } from "./server/getServerFeatureFlags";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  // Fetch feature flags from the server
  const serverFeatureFlags = await getServerFeatureFlags('demo-distinct-id');
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PostHogProviderWrapper serverFeatureFlags={serverFeatureFlags}>
          {children}
        </PostHogProviderWrapper>
      </body>
    </html>
  );
}
